[package]
name = "canhttp"
version = "0.1.0"
description = "Rust library to issue HTTPs outcalls from a canister on the Internet Computer"
license = "Apache-2.0"
readme = "README.md"
authors = ["DFINITY Foundation"]
edition = "2021"
include = ["src", "Cargo.toml", "CHANGELOG.md", "LICENSE", "README.md"]
documentation = "https://docs.rs/canhttp"

[dependencies]
ic-cdk = { workspace = true }
http = { workspace = true, optional = true }
num-traits = { workspace = true, optional = true }
pin-project = { workspace = true }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
tower = { workspace = true, features = ["filter", "retry"] }
tower-layer = { workspace = true, optional = true }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
candid = { workspace = true }
maplit = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[features]
default = ["http"]
http = ["dep:http", "dep:num-traits", "dep:tower-layer"]
json = ["http", "dep:serde", "dep:serde_json"]