[package]
name = "ic_eth_rpc"
version = "0.1.0"
description = "Ethereum on IC."
authors = ["DFINITY Foundation"]
readme = "README.md"
edition = "2021"

[profile.release]
debug = false
lto = true
opt-level = 'z'

[dependencies]
candid = "0.9"
ic-canister-log = { git = "https://github.com/dfinity/ic", rev = "release-2023-08-30_23-01" }
ic-canisters-http-types = { git = "https://github.com/dfinity/ic", rev = "release-2023-08-30_23-01" }
# ic-nervous-system-common = { git = "https://github.com/dfinity/ic", rev = "release-2023-08-30_23-01" }
# ic-certified-map = "0.4"
ic-cdk = "0.10"
ic-cdk-macros = "0.7"
ic-eth = "0.1"
ic-metrics-encoder = "1.1"
ic-stable-structures = "0.5"
ethers-providers = { version = "2.0", default-features = false }
getrandom = { version = "0.2", features = ["custom"] }
async-trait = "0.1"
num = "0.4"
num-traits = "0.2"
num-derive = "0.4"
serde = "1"
serde_json = "1.0"
url = "2.4"

[dev-dependencies]
candid = { features = ["parser"] }
hex = "0.4"
