[package]
name = "eth_rpc"
version = "0.1.0"
description = "Interact with EVM blockchains from the Internet Computer."
authors = ["DFINITY Foundation"]
readme = "README.md"
edition = "2021"

[profile.release]
debug = false
lto = true
opt-level = 'z'

[dependencies]
candid = { version = "0.9", features = ["parser"] }
ic-canister-log = { git = "https://github.com/dfinity/ic", rev = "release-2023-08-30_23-01" }
ic-canisters-http-types = { git = "https://github.com/dfinity/ic", rev = "release-2023-08-30_23-01" }
# ic-nervous-system-common = { git = "https://github.com/dfinity/ic", rev = "release-2023-08-30_23-01" }
ic-certified-map = "0.4"
ic-cdk = "0.11"
ic-cdk-macros = "0.8"
ic-eth = "0.0"
ic-metrics-encoder = "1.1"
ic-stable-structures = "0.5"
num = "0.4"
num-traits = "0.2"
num-derive = "0.4"
serde = "1"
url = "2.4"

[dev-dependencies]
hex = "0.4"

[patch.crates-io]
# wasm-bindgen = { package = "ic-wasm-bindgen", version = "0.2" }
wasm-bindgen = { git = "https://github.com/rvanasa/wasm-bindgen", branch = "ic-wasm-bindgen" }

[workspace]
members = ["lib/rust", "e2e/rust"]
