name: CI

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - "README.md"
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master

      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

      - run: rustup component add clippy

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Cargo clippy
        # We run clippy twice (once without tests), so that it accurately reports dead code in the non-test configuration.
        # `manual_range_contains` is disabled because a >= x && a < y reads more clearly than (x..y).contains(a) and
        # there are additional caveats for floating point numbers (https://github.com/rust-lang/rust-clippy/issues/6455)
        run: |
          cargo clippy -- -D clippy::all -D warnings -A clippy::manual_range_contains
          cargo clippy --tests --benches -- -D clippy::all -D warnings -A clippy::manual_range_contains

      - name: Check dependencies
        # evm_rpc_types is used in the [monorepo](https://github.com/dfinity/ic)
        # and some crates there already have a dependency on the ic-cdk. To avoid any conflicting versions of the ic-cdk,
        # we ensure that there is no transitive dependency on ic-cdk in evm_rpc_types
        run: |
          ! cargo tree -p evm_rpc_types --invert ic-cdk --locked

  cargo-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master

      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

      - run: rustup component add clippy

      - name: Cargo doc
        run: |
          cargo doc --workspace --no-deps --all-features
        env:
          RUSTDOCFLAGS: "--deny warnings"

  reproducible-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master

      - name: Docker build
        run: |
          ./scripts/docker-build

      - name: Archive Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: evm_rpc.wasm.gz
          path: evm_rpc.wasm.gz
          if-no-files-found: error

      - name: Add summary
        run: |
          hash=`sha256sum evm_rpc.wasm.gz`
          echo "SHA-256 :hash: ${hash}" >> $GITHUB_STEP_SUMMARY

  check-canister-wasm-endpoints:
    needs: [ reproducible-build ]
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: 'Download artifacts'
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: evm_rpc.wasm.gz

      - name: 'Install `ic-wasm`'
        uses: taiki-e/install-action@80e6af7a2ec7f280fffe2d0a9d3a12a9d11d86e9 # v2.75.1
        with:
          tool: ic-wasm

      - name: 'Check canister endpoints'
        run: |
          ic-wasm "$GITHUB_WORKSPACE/evm_rpc.wasm.gz" check-endpoints --hidden ./candid/hidden_endpoints.conf

  cargo-test:
    needs: [ reproducible-build ]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master

      - name: Download Artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: evm_rpc.wasm.gz
      
      - name: Set EVM_RPC_WASM_PATH for load_wasm
        run: |
          echo "EVM_RPC_WASM_PATH=$GITHUB_WORKSPACE/evm_rpc.wasm.gz" >> "$GITHUB_ENV"

      - name: Download wallet canister
        run: |
          wget https://github.com/dfinity/sdk/raw/0a82e042adec6f24ba53665312713923bf276a34/src/distributed/wallet.wasm.gz

      - name: Set WALLET_WASM_PATH for load_wasm
        run: |
          echo "WALLET_WASM_PATH=$GITHUB_WORKSPACE/wallet.wasm.gz" >> "$GITHUB_ENV"
 
      - name: Install PocketIC server
        uses: dfinity/pocketic@20c33db1aa87cc6ece50857ac632c37acf5e0322 # main
        with:
          pocket-ic-server-version: "12.0.0"

      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

      - name: Cargo test
        run: cargo test --workspace --all-features -- --test-threads=2 --nocapture

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@61b9e3751b92087fd0b06925ba6dd6314e06f089 # master

      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2

      - name: Install icp-cli
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/dfinity/icp-cli/releases/download/v0.2.3/icp-cli-installer.sh | sh
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Install didc
        run: |
          sudo curl -sSL "https://github.com/dfinity/candid/releases/latest/download/didc-linux64" -o /usr/local/bin/didc
          sudo chmod +x /usr/local/bin/didc

      - name: Install ic-wasm
        uses: taiki-e/install-action@80e6af7a2ec7f280fffe2d0a9d3a12a9d11d86e9 # v2.75.1
        with:
          tool: ic-wasm

      - name: Install mops (Motoko toolchain manager)
        run: |
          curl -fsSL cli.mops.one/install.sh | sh
          echo "$HOME/.mops/bin" >> "$GITHUB_PATH"

      - name: Start local network
        run: icp network start -d

      - name: Install npm packages
        run: npm ci

      - name: Run E2E tests
        run: scripts/e2e

      - name: Run examples
        run: scripts/examples evm_rpc 'Number = 20000000'

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@8789b3e21e6c11b2697f5eb56eddae542f746c10 # v1.7.0

      - name: Run anvil
        run: anvil &

      - name: Run local examples with Foundry
        run: scripts/examples evm_rpc_local 'Number = 0'
